package cn.jstorm.outdoor.model;

import java.util.Date;

public class ODAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_table.account_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_table.create_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_table.update_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_table.delete_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_table.update_user
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_table.state
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_table.account_role
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String accountRole;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_table.account_id
     *
     * @return the value of account_table.account_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_table.account_id
     *
     * @param accountId the value for account_table.account_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_table.create_time
     *
     * @return the value of account_table.create_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_table.create_time
     *
     * @param createTime the value for account_table.create_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_table.update_time
     *
     * @return the value of account_table.update_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_table.update_time
     *
     * @param updateTime the value for account_table.update_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_table.delete_time
     *
     * @return the value of account_table.delete_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_table.delete_time
     *
     * @param deleteTime the value for account_table.delete_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_table.update_user
     *
     * @return the value of account_table.update_user
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_table.update_user
     *
     * @param updateUser the value for account_table.update_user
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_table.state
     *
     * @return the value of account_table.state
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_table.state
     *
     * @param state the value for account_table.state
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_table.account_role
     *
     * @return the value of account_table.account_role
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getAccountRole() {
        return accountRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_table.account_role
     *
     * @param accountRole the value for account_table.account_role
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setAccountRole(String accountRole) {
        this.accountRole = accountRole == null ? null : accountRole.trim();
    }
}