package cn.jstorm.outdoor.model;

public class ODColleges {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colleges_table.college_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String collegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colleges_table.college_name
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String collegeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colleges_table.college_blank
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String collegeBlank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colleges_table.college_desc
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String collegeDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colleges_table.college_id
     *
     * @return the value of colleges_table.college_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colleges_table.college_id
     *
     * @param collegeId the value for colleges_table.college_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setCollegeId(String collegeId) {
        this.collegeId = collegeId == null ? null : collegeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colleges_table.college_name
     *
     * @return the value of colleges_table.college_name
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getCollegeName() {
        return collegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colleges_table.college_name
     *
     * @param collegeName the value for colleges_table.college_name
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName == null ? null : collegeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colleges_table.college_blank
     *
     * @return the value of colleges_table.college_blank
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getCollegeBlank() {
        return collegeBlank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colleges_table.college_blank
     *
     * @param collegeBlank the value for colleges_table.college_blank
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setCollegeBlank(String collegeBlank) {
        this.collegeBlank = collegeBlank == null ? null : collegeBlank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colleges_table.college_desc
     *
     * @return the value of colleges_table.college_desc
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getCollegeDesc() {
        return collegeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colleges_table.college_desc
     *
     * @param collegeDesc the value for colleges_table.college_desc
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setCollegeDesc(String collegeDesc) {
        this.collegeDesc = collegeDesc == null ? null : collegeDesc.trim();
    }
}