package cn.jstorm.outdoor.model;

public class ODPzone {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pzone_table.zone_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String zoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pzone_table.zone_content
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String zoneContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pzone_table.zone_remark
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String zoneRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pzone_table.zone_pic
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String zonePic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pzone_table.zone_id
     *
     * @return the value of pzone_table.zone_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pzone_table.zone_id
     *
     * @param zoneId the value for pzone_table.zone_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setZoneId(String zoneId) {
        this.zoneId = zoneId == null ? null : zoneId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pzone_table.zone_content
     *
     * @return the value of pzone_table.zone_content
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getZoneContent() {
        return zoneContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pzone_table.zone_content
     *
     * @param zoneContent the value for pzone_table.zone_content
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setZoneContent(String zoneContent) {
        this.zoneContent = zoneContent == null ? null : zoneContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pzone_table.zone_remark
     *
     * @return the value of pzone_table.zone_remark
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getZoneRemark() {
        return zoneRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pzone_table.zone_remark
     *
     * @param zoneRemark the value for pzone_table.zone_remark
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setZoneRemark(String zoneRemark) {
        this.zoneRemark = zoneRemark == null ? null : zoneRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pzone_table.zone_pic
     *
     * @return the value of pzone_table.zone_pic
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getZonePic() {
        return zonePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pzone_table.zone_pic
     *
     * @param zonePic the value for pzone_table.zone_pic
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setZonePic(String zonePic) {
        this.zonePic = zonePic == null ? null : zonePic.trim();
    }
}