package cn.jstorm.outdoor.model;

import java.util.Date;

public class ODRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_table.record_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_table.reply_user
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String replyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_table.reply_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private Date replyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_table.record_state
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private Integer recordState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_table.record_content
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String recordContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_table.post_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_table.zone_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String zoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_table.user_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_table.record_auditor
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String recordAuditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_table.auditor_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private Date auditorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_table.record_id
     *
     * @return the value of record_table.record_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_table.record_id
     *
     * @param recordId the value for record_table.record_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_table.reply_user
     *
     * @return the value of record_table.reply_user
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getReplyUser() {
        return replyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_table.reply_user
     *
     * @param replyUser the value for record_table.reply_user
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setReplyUser(String replyUser) {
        this.replyUser = replyUser == null ? null : replyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_table.reply_time
     *
     * @return the value of record_table.reply_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public Date getReplyTime() {
        return replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_table.reply_time
     *
     * @param replyTime the value for record_table.reply_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setReplyTime(Date replyTime) {
        this.replyTime = replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_table.record_state
     *
     * @return the value of record_table.record_state
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public Integer getRecordState() {
        return recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_table.record_state
     *
     * @param recordState the value for record_table.record_state
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setRecordState(Integer recordState) {
        this.recordState = recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_table.record_content
     *
     * @return the value of record_table.record_content
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getRecordContent() {
        return recordContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_table.record_content
     *
     * @param recordContent the value for record_table.record_content
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setRecordContent(String recordContent) {
        this.recordContent = recordContent == null ? null : recordContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_table.post_id
     *
     * @return the value of record_table.post_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_table.post_id
     *
     * @param postId the value for record_table.post_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setPostId(String postId) {
        this.postId = postId == null ? null : postId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_table.zone_id
     *
     * @return the value of record_table.zone_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_table.zone_id
     *
     * @param zoneId the value for record_table.zone_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setZoneId(String zoneId) {
        this.zoneId = zoneId == null ? null : zoneId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_table.user_id
     *
     * @return the value of record_table.user_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_table.user_id
     *
     * @param userId the value for record_table.user_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_table.record_auditor
     *
     * @return the value of record_table.record_auditor
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getRecordAuditor() {
        return recordAuditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_table.record_auditor
     *
     * @param recordAuditor the value for record_table.record_auditor
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setRecordAuditor(String recordAuditor) {
        this.recordAuditor = recordAuditor == null ? null : recordAuditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_table.auditor_time
     *
     * @return the value of record_table.auditor_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public Date getAuditorTime() {
        return auditorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_table.auditor_time
     *
     * @param auditorTime the value for record_table.auditor_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setAuditorTime(Date auditorTime) {
        this.auditorTime = auditorTime;
    }
}