package cn.jstorm.outdoor.model;

import java.io.Serializable;
import java.util.Date;

/**
 * 普通用户模型
 * @author jstorm
 *
 */
public class ODUser implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 4260247357271838578L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.user_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.user_name
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.real_name
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.user_mobile
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.user_sex
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private Integer userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.user_age
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private Integer userAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.user_birthday
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private Date userBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.user_mail
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String userMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.create_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.update_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.delete_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.update_user
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.user_desc
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String userDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.colleges_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private String collegesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.is_account
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private Byte isAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.state
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.user_id
     *
     * @return the value of user_table.user_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.user_id
     *
     * @param userId the value for user_table.user_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.user_name
     *
     * @return the value of user_table.user_name
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.user_name
     *
     * @param userName the value for user_table.user_name
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.real_name
     *
     * @return the value of user_table.real_name
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.real_name
     *
     * @param realName the value for user_table.real_name
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.user_mobile
     *
     * @return the value of user_table.user_mobile
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.user_mobile
     *
     * @param userMobile the value for user_table.user_mobile
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.user_sex
     *
     * @return the value of user_table.user_sex
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public Integer getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.user_sex
     *
     * @param userSex the value for user_table.user_sex
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.user_age
     *
     * @return the value of user_table.user_age
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.user_age
     *
     * @param userAge the value for user_table.user_age
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.user_birthday
     *
     * @return the value of user_table.user_birthday
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.user_birthday
     *
     * @param userBirthday the value for user_table.user_birthday
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.user_mail
     *
     * @return the value of user_table.user_mail
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getUserMail() {
        return userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.user_mail
     *
     * @param userMail the value for user_table.user_mail
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setUserMail(String userMail) {
        this.userMail = userMail == null ? null : userMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.create_time
     *
     * @return the value of user_table.create_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.create_time
     *
     * @param createTime the value for user_table.create_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.update_time
     *
     * @return the value of user_table.update_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.update_time
     *
     * @param updateTime the value for user_table.update_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.delete_time
     *
     * @return the value of user_table.delete_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.delete_time
     *
     * @param deleteTime the value for user_table.delete_time
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.update_user
     *
     * @return the value of user_table.update_user
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.update_user
     *
     * @param updateUser the value for user_table.update_user
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.user_desc
     *
     * @return the value of user_table.user_desc
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getUserDesc() {
        return userDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.user_desc
     *
     * @param userDesc the value for user_table.user_desc
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setUserDesc(String userDesc) {
        this.userDesc = userDesc == null ? null : userDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.colleges_id
     *
     * @return the value of user_table.colleges_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public String getCollegesId() {
        return collegesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.colleges_id
     *
     * @param collegesId the value for user_table.colleges_id
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setCollegesId(String collegesId) {
        this.collegesId = collegesId == null ? null : collegesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.is_account
     *
     * @return the value of user_table.is_account
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public Byte getIsAccount() {
        return isAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.is_account
     *
     * @param isAccount the value for user_table.is_account
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setIsAccount(Byte isAccount) {
        this.isAccount = isAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.state
     *
     * @return the value of user_table.state
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.state
     *
     * @param state the value for user_table.state
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    public void setState(Integer state) {
        this.state = state;
    }

	@Override
	public String toString() {
		return "ODUser [userId=" + userId + ", userName=" + userName
				+ ", realName=" + realName + ", userMobile=" + userMobile
				+ ", userSex=" + userSex + ", userAge=" + userAge
				+ ", userBirthday=" + userBirthday + ", userMail=" + userMail
				+ ", createTime=" + createTime + ", updateTime=" + updateTime
				+ ", deleteTime=" + deleteTime + ", updateUser=" + updateUser
				+ ", userDesc=" + userDesc + ", collegesId=" + collegesId
				+ ", isAccount=" + isAccount + ", state=" + state + "]";
	}
    
    
}