package cn.jstorm.outdoor.dao;

import cn.jstorm.outdoor.model.ODColleges;

public interface ODCollegesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int deleteByPrimaryKey(String collegeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int insert(ODColleges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int insertSelective(ODColleges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    ODColleges selectByPrimaryKey(String collegeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int updateByPrimaryKeySelective(ODColleges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int updateByPrimaryKey(ODColleges record);
}