package cn.jstorm.outdoor.dao;

import cn.jstorm.outdoor.model.ODPostType;

public interface ODPostTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_type
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int deleteByPrimaryKey(String typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_type
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int insert(ODPostType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_type
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int insertSelective(ODPostType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_type
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    ODPostType selectByPrimaryKey(String typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_type
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int updateByPrimaryKeySelective(ODPostType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_type
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int updateByPrimaryKey(ODPostType record);
}