package cn.jstorm.outdoor.dao;

import cn.jstorm.outdoor.model.ODPost;

public interface ODPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int deleteByPrimaryKey(Integer postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int insert(ODPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int insertSelective(ODPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    ODPost selectByPrimaryKey(Integer postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int updateByPrimaryKeySelective(ODPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int updateByPrimaryKey(ODPost record);
}