package cn.jstorm.outdoor.dao;

import cn.jstorm.outdoor.model.ODPzone;

public interface ODPzoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pzone_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int deleteByPrimaryKey(String zoneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pzone_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int insert(ODPzone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pzone_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int insertSelective(ODPzone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pzone_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    ODPzone selectByPrimaryKey(String zoneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pzone_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int updateByPrimaryKeySelective(ODPzone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pzone_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int updateByPrimaryKey(ODPzone record);
}