package cn.jstorm.outdoor.dao;

import cn.jstorm.outdoor.model.ODRecord;

public interface ODRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int deleteByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int insert(ODRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int insertSelective(ODRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    ODRecord selectByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int updateByPrimaryKeySelective(ODRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int updateByPrimaryKey(ODRecord record);
}