package cn.jstorm.outdoor.dao;

import cn.jstorm.outdoor.model.ODRole;

public interface ODRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int insert(ODRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int insertSelective(ODRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    ODRole selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int updateByPrimaryKeySelective(ODRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_table
     *
     * @mbggenerated Tue Aug 18 21:56:09 CST 2015
     */
    int updateByPrimaryKey(ODRole record);
}